### ISSUE TITLE
Text has low contrast on Help, Stats, and All Cards

### ISSUE THREAD

**Issue by ecashin** [ecashin/memoradical#37]
The new styling looks great, but the font colors in my Chrome browser are not easy to read against their light backgrounds.  I'll attach some screenshots.
![all-cards](https://github.com/ecashin/memoradical/assets/1819269/b177f700-53b7-4eaf-a795-add5a0d360b6)
![stats](https://github.com/ecashin/memoradical/assets/1819269/11774771-cdb0-4daa-83c8-2354b854baa4)
![help](https://github.com/ecashin/memoradical/assets/1819269/c6d6be1b-dbab-4feb-9c90-da2d1268bc86)

**Comment by bbenne10** [comment]
Whoops. I didn't test this flow. I should have done that.

**Comment by bbenne10** [comment]
Investigation leads to a few findings:

- pages other than the "study" view don't have a "memoradical" id on the root div, which is what causes the nav to switch to a differing style (but that's not what this issue is about)
- The root problem is a rule that I decided not to touch. Changing the below color from `#dde` to `slategray` works for me, but maybe is not enough contrast between rows for you?
```css
table.striped tr:nth-of-type(odd) {
    background-color: #dde; /* change to slategray */
    padding: 1ex;
}
```



- There aren't enough `th`s in the header row to pad it out to the end so the result looks a bit goofy

**Comment by ecashin** [comment]
Hello.  Are you still interested in following up on the style changes?

**Comment by ecashin** [comment]
> Investigation leads to a few findings:
> 
> * pages other than the "study" view don't have a "memoradical" id on the root div, which is what causes the nav to switch to a differing style (but that's not what this issue is about)
> * The root problem is a rule that I decided not to touch. Changing the below color from `#dde` to `slategray` works for me, but maybe is not enough contrast between rows for you?
> 
> ```css
> table.striped tr:nth-of-type(odd) {
>     background-color: #dde; /* change to slategray */
>     padding: 1ex;
> }
> ```
> 
> * There aren't enough `th`s in the header row to pad it out to the end so the result looks a bit goofy

If it looks good to you, it would be great if you would push to a fix branch.  Or you could put a screenshot here if you just want feedback on specific color contrasts.

Thanks.

**Comment by bbenne10** [comment]
Setting up a rust development pipeline is not something I am terribly interested in doing after work hours, honestly.
Especially when this isn't rooted in the Rust code at all and can be tested pretty easily with modern developer tools in Firefox and Chrome. I went ahead and applied the whole new style sheet to the instance running at https://ecashin.github.io/memoradical/ and then modified it with the rule change I mentioned in my last comment and it looks like so:
![image](https://github.com/ecashin/memoradical/assets/687376/8eaf757e-d1ad-4044-9ab5-7074ed854722)

And this is the appearance when adding the "memoradical" id to the root div *and* the CSS change above:
![image](https://github.com/ecashin/memoradical/assets/687376/7adc3977-ce98-4050-97fb-5b806b96eeea)

**Comment by bbenne10** [comment]
The help page is incorrectly styled due to presently having *no* presentational classes applied anywhere coupled with some over general styling on the "Study" pane. If one of two things happened, we could better scope our styling:

* A per page class that is applied to the root div (so `<body><div id="memoradical" class="study"> ...`) or...
* better application of presentational css classes in general (so `<p class="card">...</p>` rather than the inline styling we have now)

Either of these requires changes to the component structure (and as discussed elsewhere, I find making contributions there a bit daunting, given the length and complexity of the code there), so I have not investigated making those changes as of yet (and frankly do not intend to do so).
